/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabio
 */
public class MenuFrame extends javax.swing.JFrame {

     private Usuario usuarioLogado;
    
    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    
    public MenuFrame(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        System.out.println("Usuario logado: " + usuarioLogado.getNomeUsuario());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_spotifeiMenu = new javax.swing.JLabel();
        bt_voltarMenu = new javax.swing.JButton();
        bt_playlistsMenu = new javax.swing.JButton();
        bt_pesquisarMenu = new javax.swing.JButton();
        bt_historicoMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 20, 20));

        lbl_spotifeiMenu.setBackground(new java.awt.Color(30, 215, 96));
        lbl_spotifeiMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_spotifeiMenu.setForeground(new java.awt.Color(25, 20, 20));
        lbl_spotifeiMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_spotifeiMenu.setText("SPOTIFEI");
        lbl_spotifeiMenu.setToolTipText("");

        bt_voltarMenu.setText("<-- Desconectar");
        bt_voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarMenuActionPerformed(evt);
            }
        });

        bt_playlistsMenu.setBackground(new java.awt.Color(25, 20, 20));
        bt_playlistsMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_playlistsMenu.setForeground(new java.awt.Color(30, 215, 96));
        bt_playlistsMenu.setText("Playlists");

        bt_pesquisarMenu.setBackground(new java.awt.Color(25, 20, 20));
        bt_pesquisarMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_pesquisarMenu.setForeground(new java.awt.Color(30, 215, 96));
        bt_pesquisarMenu.setText("Pesquisar");
        bt_pesquisarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarMenuActionPerformed(evt);
            }
        });

        bt_historicoMenu.setBackground(new java.awt.Color(25, 20, 20));
        bt_historicoMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_historicoMenu.setForeground(new java.awt.Color(30, 215, 96));
        bt_historicoMenu.setText("Histórico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_voltarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_pesquisarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_playlistsMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_spotifeiMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(bt_historicoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_voltarMenu)
                    .addComponent(lbl_spotifeiMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(bt_pesquisarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_playlistsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_historicoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_pesquisarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarMenuActionPerformed
        if (this.usuarioLogado != null) {
        PesquisaFrame pesquisarView = new PesquisaFrame(this.usuarioLogado);
        pesquisarView.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Erro: Usuário não está logado.", "Erro", JOptionPane.ERROR_MESSAGE);
        LoginFrame loginView = new LoginFrame();
        loginView.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_bt_pesquisarMenuActionPerformed

    private void bt_voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarMenuActionPerformed
        LoginFrame loginView = new LoginFrame();
        loginView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_voltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_historicoMenu;
    private javax.swing.JButton bt_pesquisarMenu;
    private javax.swing.JButton bt_playlistsMenu;
    private javax.swing.JButton bt_voltarMenu;
    private javax.swing.JLabel lbl_spotifeiMenu;
    // End of variables declaration//GEN-END:variables
}
