/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerPesquisa;
import model.Musica;
import model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class PesquisaFrame extends javax.swing.JFrame {

    private ControllerPesquisa controller;
    private Usuario usuarioLogado;
    
    /**
     * Creates new form PesquisaFrame
     */
    public PesquisaFrame(Usuario usuario) {
        initComponents();
        
        bt_curtirPesquisa.setEnabled(false);
        bt_descurtirPesquisa.setEnabled(false);
        
        table_resultadoPesquisa.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    boolean linhaSelecionada = table_resultadoPesquisa.getSelectedRow() != -1;
                    bt_curtirPesquisa.setEnabled(linhaSelecionada);
                    bt_descurtirPesquisa.setEnabled(linhaSelecionada);
                }
            }
        });
        
        
        this.usuarioLogado = usuario;
        this.controller = new ControllerPesquisa(this, this.usuarioLogado);
    }

    public JTextField getTxt_termoPesquisa() {
        return txt_termoPesquisa;
    }
    
    public void atualizarTabelaMusicas(List<Musica> musicas, String termoOriginal) {
        String[] colunas = {"ID", "Nome", "Autor", "Gênero"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    
        if (musicas != null) {
            for (Musica musica : musicas) {
                model.addRow(new Object[]{
                    musica.getIdMusica(),
                    musica.getNomeMusica(),
                    musica.getAutorMusica(),
                    musica.getGeneroMusica()
                });
            }
        }
        
        table_resultadoPesquisa.setModel(model);
        
        if (musicas != null && musicas.isEmpty() && termoOriginal != null && !termoOriginal.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhuma música encontrada para '" + termoOriginal + "'.", "Sem resultados", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void popularTabelaMusicas(List<Musica> musicas, String termoOriginal) {
    String[] colunas = {"ID", "Nome", "Autor", "Gênero"};
    DefaultTableModel model = new DefaultTableModel(colunas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    if (musicas != null) {
        for (Musica musica : musicas) {
            model.addRow(new Object[]{
                musica.getIdMusica(),
                musica.getNomeMusica(),
                musica.getAutorMusica(),
                musica.getGeneroMusica()
            });
        }
    }

    table_resultadoPesquisa.setModel(model);

    if (musicas != null && musicas.isEmpty() && termoOriginal != null && !termoOriginal.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhuma música encontrada para '" + termoOriginal + "'.", "Sem resultados", JOptionPane.INFORMATION_MESSAGE);
    }
}
    
    public void limparTabela() {
    DefaultTableModel model = (DefaultTableModel) table_resultadoPesquisa.getModel();
    model.setRowCount(0);
}
     
    public int getIdMusicaSelecionada() {
        int linhaSelecionada = table_resultadoPesquisa.getSelectedRow();
        if (linhaSelecionada != -1) {
            Object idObj = table_resultadoPesquisa.getValueAt(linhaSelecionada, 0);
            if (idObj instanceof Integer) {
                return (Integer) idObj;
            } else {
                try {
                    return Integer.parseInt(idObj.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Erro ao converter ID da música para Inteiro: " + idObj);
                    return -1;
                }
            }
        }
        return -1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_spotifeiPesquisa = new javax.swing.JLabel();
        bt_voltarPesquisa = new javax.swing.JButton();
        txt_termoPesquisa = new javax.swing.JTextField();
        bt_pesquisarPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_resultadoPesquisa = new javax.swing.JTable();
        bt_curtirPesquisa = new javax.swing.JButton();
        bt_descurtirPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_spotifeiPesquisa.setBackground(new java.awt.Color(30, 215, 96));
        lbl_spotifeiPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_spotifeiPesquisa.setForeground(new java.awt.Color(25, 20, 20));
        lbl_spotifeiPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_spotifeiPesquisa.setText("SPOTIFEI");
        lbl_spotifeiPesquisa.setToolTipText("");

        bt_voltarPesquisa.setText("<-- Voltar");
        bt_voltarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarPesquisaActionPerformed(evt);
            }
        });

        txt_termoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_termoPesquisaActionPerformed(evt);
            }
        });

        bt_pesquisarPesquisa.setBackground(new java.awt.Color(25, 20, 20));
        bt_pesquisarPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_pesquisarPesquisa.setForeground(new java.awt.Color(30, 215, 96));
        bt_pesquisarPesquisa.setText("Pesquisar!");
        bt_pesquisarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarPesquisaActionPerformed(evt);
            }
        });

        table_resultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_resultadoPesquisa);

        bt_curtirPesquisa.setBackground(new java.awt.Color(30, 215, 96));
        bt_curtirPesquisa.setText("👍");
        bt_curtirPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtirPesquisaActionPerformed(evt);
            }
        });

        bt_descurtirPesquisa.setBackground(new java.awt.Color(215, 30, 96));
        bt_descurtirPesquisa.setText("👎");
        bt_descurtirPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_descurtirPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_voltarPesquisa)
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_termoPesquisa)
                            .addComponent(lbl_spotifeiPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(bt_pesquisarPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(179, 179, 179)
                        .addComponent(bt_curtirPesquisa)
                        .addGap(47, 47, 47)
                        .addComponent(bt_descurtirPesquisa)
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_spotifeiPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltarPesquisa))
                .addGap(30, 30, 30)
                .addComponent(txt_termoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_pesquisarPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_curtirPesquisa)
                    .addComponent(bt_descurtirPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarPesquisaActionPerformed
        if (this.usuarioLogado != null) {
            MenuFrame mf = new MenuFrame(this.usuarioLogado);
            mf.setVisible(true);
        } else {
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_bt_voltarPesquisaActionPerformed

    private void bt_pesquisarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarPesquisaActionPerformed
        if (controller != null) {
            controller.pesquisarMusicas();
        }
    }//GEN-LAST:event_bt_pesquisarPesquisaActionPerformed

    private void txt_termoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_termoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_termoPesquisaActionPerformed

    private void bt_curtirPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtirPesquisaActionPerformed
        if (controller != null) {
            controller.processarCurtidaMusica();
        }
    }//GEN-LAST:event_bt_curtirPesquisaActionPerformed

    private void bt_descurtirPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_descurtirPesquisaActionPerformed
        if (controller != null) {
            controller.processarDescurtidaMusica();
        }
    }//GEN-LAST:event_bt_descurtirPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PesquisaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PesquisaFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_curtirPesquisa;
    private javax.swing.JButton bt_descurtirPesquisa;
    private javax.swing.JButton bt_pesquisarPesquisa;
    private javax.swing.JButton bt_voltarPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_spotifeiPesquisa;
    private javax.swing.JTable table_resultadoPesquisa;
    private javax.swing.JTextField txt_termoPesquisa;
    // End of variables declaration//GEN-END:variables
}
