/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author fabio
 */
public class PlaylistFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistFrame
     */
    public PlaylistFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_spotifeiPlaylist = new javax.swing.JLabel();
        bt_voltarPlaylist = new javax.swing.JButton();
        tab_painelPlaylist = new javax.swing.JTabbedPane();
        jpanel_criarPlaylist = new javax.swing.JPanel();
        txt_nomePlaylist = new javax.swing.JTextField();
        lbl_nomePlaylist = new javax.swing.JLabel();
        bt_criarPlaylist = new javax.swing.JButton();
        jpanel_apagarPlaylist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_apagarPlaylist = new javax.swing.JTable();
        bt_apagarPlaylist = new javax.swing.JButton();
        jpanel_editarPlaylist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_musicasPlaylist = new javax.swing.JTable();
        bt_confirmarnomePlaylist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_novonomePlaylist = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_renamePlaylist = new javax.swing.JTable();
        bt_removermusicaPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_spotifeiPlaylist.setBackground(new java.awt.Color(30, 215, 96));
        lbl_spotifeiPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_spotifeiPlaylist.setForeground(new java.awt.Color(25, 20, 20));
        lbl_spotifeiPlaylist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_spotifeiPlaylist.setText("SPOTIFEI");
        lbl_spotifeiPlaylist.setToolTipText("");

        bt_voltarPlaylist.setBackground(new java.awt.Color(25, 20, 20));
        bt_voltarPlaylist.setForeground(new java.awt.Color(30, 215, 96));
        bt_voltarPlaylist.setText("<-- Voltar");
        bt_voltarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarPlaylistActionPerformed(evt);
            }
        });

        lbl_nomePlaylist.setText("Nome da playlist:");

        bt_criarPlaylist.setBackground(new java.awt.Color(25, 20, 20));
        bt_criarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_criarPlaylist.setForeground(new java.awt.Color(30, 215, 96));
        bt_criarPlaylist.setText("Confirmar!");

        javax.swing.GroupLayout jpanel_criarPlaylistLayout = new javax.swing.GroupLayout(jpanel_criarPlaylist);
        jpanel_criarPlaylist.setLayout(jpanel_criarPlaylistLayout);
        jpanel_criarPlaylistLayout.setHorizontalGroup(
            jpanel_criarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_criarPlaylistLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lbl_nomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(bt_criarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jpanel_criarPlaylistLayout.setVerticalGroup(
            jpanel_criarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_criarPlaylistLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jpanel_criarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nomePlaylist)
                    .addComponent(bt_criarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        tab_painelPlaylist.addTab("Criar Playlist", jpanel_criarPlaylist);

        table_apagarPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_apagarPlaylist);

        bt_apagarPlaylist.setBackground(new java.awt.Color(215, 30, 96));
        bt_apagarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_apagarPlaylist.setText("Apagar!");

        javax.swing.GroupLayout jpanel_apagarPlaylistLayout = new javax.swing.GroupLayout(jpanel_apagarPlaylist);
        jpanel_apagarPlaylist.setLayout(jpanel_apagarPlaylistLayout);
        jpanel_apagarPlaylistLayout.setHorizontalGroup(
            jpanel_apagarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_apagarPlaylistLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(bt_apagarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jpanel_apagarPlaylistLayout.setVerticalGroup(
            jpanel_apagarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_apagarPlaylistLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpanel_apagarPlaylistLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(bt_apagarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_painelPlaylist.addTab("Apagar Playlist", jpanel_apagarPlaylist);

        table_musicasPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_musicasPlaylist);

        bt_confirmarnomePlaylist.setBackground(new java.awt.Color(25, 20, 20));
        bt_confirmarnomePlaylist.setForeground(new java.awt.Color(30, 215, 96));
        bt_confirmarnomePlaylist.setText("Confirmar");

        jLabel1.setText("Novo nome playlist:");

        table_renamePlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_renamePlaylist);

        bt_removermusicaPlaylist.setBackground(new java.awt.Color(215, 30, 96));
        bt_removermusicaPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_removermusicaPlaylist.setText("Remover Música!");

        javax.swing.GroupLayout jpanel_editarPlaylistLayout = new javax.swing.GroupLayout(jpanel_editarPlaylist);
        jpanel_editarPlaylist.setLayout(jpanel_editarPlaylistLayout);
        jpanel_editarPlaylistLayout.setHorizontalGroup(
            jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                .addGroup(jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_editarPlaylistLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                        .addGroup(jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(bt_confirmarnomePlaylist))
                            .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txt_novonomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_removermusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jpanel_editarPlaylistLayout.setVerticalGroup(
            jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_editarPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel_editarPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_novonomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_removermusicaPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_confirmarnomePlaylist)
                .addGap(22, 22, 22))
        );

        tab_painelPlaylist.addTab("Editar Playlist", jpanel_editarPlaylist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_voltarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254)
                .addComponent(lbl_spotifeiPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tab_painelPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_spotifeiPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltarPlaylist))
                .addGap(18, 18, 18)
                .addComponent(tab_painelPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_voltarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarPlaylistActionPerformed
//        if (this.usuarioLogado != null) {
//            MenuFrame mf = new MenuFrame(this.usuarioLogado);
//            mf.setVisible(true);
//        } else {
//            LoginFrame lf = new LoginFrame();
//            lf.setVisible(true);
//        }
//        this.dispose();
    }//GEN-LAST:event_bt_voltarPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_apagarPlaylist;
    private javax.swing.JButton bt_confirmarnomePlaylist;
    private javax.swing.JButton bt_criarPlaylist;
    private javax.swing.JButton bt_removermusicaPlaylist;
    private javax.swing.JButton bt_voltarPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpanel_apagarPlaylist;
    private javax.swing.JPanel jpanel_criarPlaylist;
    private javax.swing.JPanel jpanel_editarPlaylist;
    private javax.swing.JLabel lbl_nomePlaylist;
    private javax.swing.JLabel lbl_spotifeiPlaylist;
    private javax.swing.JTabbedPane tab_painelPlaylist;
    private javax.swing.JTable table_apagarPlaylist;
    private javax.swing.JTable table_musicasPlaylist;
    private javax.swing.JTable table_renamePlaylist;
    private javax.swing.JTextField txt_nomePlaylist;
    private javax.swing.JTextField txt_novonomePlaylist;
    // End of variables declaration//GEN-END:variables
}
